spring.cloud.stream:
  function:
    definition: jokeConsumerService
  bindings:
    domainService-in-0:
      destination: safe-joke
  kafka:
    bindings:
      domainService-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    binder:
      brokers:
        - 127.0.0.1:9092